### ISSUE TITLE
Add header settings got ignored

### ISSUE THREAD

**Issue by unmec** [hao1300/modheader#1]
Thanks for the extension which seems very promising, except add header dosesn't really work on my settings:

ModHeader: 2.3.2 (Chrome Web Store version)
Chromium: 75.0.3770.100 64-bit

**Comment by hao1300** [comment]
Can you go to chrome://extensions/, turn on "Developer mode", look for ModHeader and click on "background page". Let me know if you see any exception in the console there.

Also, did you set any filter, or use Tab lock, or pause ModHeader by any chance?

**Comment by unmec** [comment]
Hi there, thanks for the hint. I just took ran my case again with:

ModHeader: 2.3.***4*** (Chrome Web Store version)
Chromium: 75.0.3770.100 64-bit

**It works fine now.** There are no error in console on background page with developer mode enabled.

I had another extension installed called [Disable Javascript](https://chrome.google.com/webstore/detail/disable-javascript/jfpdlihdedhlmhlbgooailmfhahieoem) which also plays with Content Security Policy header, it might be the cause that ModHeader 2.3.2 ignored my response header settings few days ago.

Anyway I am happy that it works as expected. It would be even better if we could apply the settings with a per site basis. ;-)

Thanks!

**Comment by hao1300** [comment]
Great. Closing this issue.
