### ISSUE TITLE
Option to disable tips

### ISSUE THREAD

**Issue by jkrehm** [hao1300/modheader#3]
First, thank you for an awesome and useful extension.

Would consider either accepting a PR that adds the ability to disable tips, or add that option yourself?

One of my profiles has 12 headers (I toggle them on and off) and my most used ones are at the bottom, where the tips show up. I can't sort them to the top (without deleting everything above) so I have to wait a few seconds for the tip to go away before I can click the headers that I want. It's not a big deal, but it is an annoyance.

**Comment by hao1300** [comment]
Just fixed this. There is a "Dismiss" button to close the tip. After dismissing 3 times it will not show up again.

**Comment by jkrehm** [comment]
Awesome, thank you!
