### ISSUE TITLE
Tab lock is active

### ISSUE THREAD

**Issue by scooper91** [hao1300/modheader#6]
Hi!

I've been using this plugin for a couple of years without any issues.  When I went to use it last week, it said that it is paused because tab lock is active (see screenshot below).  It also happens in Incognito mode when there are no other extensions enabled.

![image](https://user-images.githubusercontent.com/8831320/62469917-2c20d180-b791-11e9-9815-5ff999aaf919.png)

Do you have any ideas what is causing this?

Thanks,

Sophie

**Comment by hao1300** [comment]
Can you open up the console to see if there is any error? To open up the console, right click within the extension's popup, and click "Inspect", then go to the "Console" tab.

**Comment by scooper91** [comment]
Thanks for the quick reply!  There are the following console errors:
 
![image](https://user-images.githubusercontent.com/8831320/62478742-be31d580-b7a3-11e9-99db-41a73d3f4e04.png)

**Comment by hao1300** [comment]
It appears that your profiles somehow got corrupted. Can you follow the instructions above, but instead of going to the Console tab, go to the Application tab, then look for "Local Storage", expand and click on the chrome-extension://..., on the right side, click on the profiles entry, and replace its value with

```
[{"title":"Profile 1","hideComment":true,"headers":[{"enabled":true,"name":"","value":"","comment":""}],"respHeaders":[],"filters":[],"appendMode":"","alwaysModifyCorsRequest":""}]
```

This should help reset your profiles.

**Comment by scooper91** [comment]
Ahh yeah `profiles` was set to `0` for some reason! It's working now I've changed it to as above (although obviously it's lost all the headers I had, but that's fine).

Does local storage sync between browsers?  I originally saw the issue on my laptop (same chrome profile), and saw the same issue on my work computer.

Thanks for your help!

**Comment by hao1300** [comment]
Local storage doesn't sync, but ModHeader does save to your Chrome's sync storage as backup, and will attempt to sync it to your other computer's local storage on initial install when local storage is empty.
