### ISSUE TITLE
header does not get applied unless profile is set to cors request modification = always

### ISSUE THREAD

**Issue by kenglxn** [hao1300/modheader#7]
First off, thank you for the awesome chrome extension :)

Seems like there has been a regression very recently that is causing a header to not be applied to some requests. This worked just a week ago, so I believe it is a recent regression.

I have an app hosted on a url on localhost (`http://localhost:4200/web/foo`), but requests to `http://localhost:4200/api/foo/bar` do not get the header applied. Although requests to `http://localhost:4200/logg` do.

If i set cors request modification = always in profile settings, it works as it did before.

What do you think? Is this a bug/regression?

**Comment by kenglxn** [comment]
It also works as it did before, if I set any header in the axios/xhr. Even foo: bar. Then the header gets applied from the mod header profile even with 'safe-defaults'.

**Comment by hao1300** [comment]
Yea, all of that was to work around a regression in Chrome 76. Now that Chrome actually properly document how to fix it, I have submitted https://github.com/hao1300/modheader/commit/638af31cffb88447f9b38d4a42c31ce183820e9a to undo those changes. It should work as before now.

**Comment by kenglxn** [comment]
Thank you
